apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-service
  labels:
    app: springboot-k8s-service
spec:
  ports:
    - port: 9000
      protocol: TCP
  type: NodePort
  selector:
    app: spring-hello-world